# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 2.6.3'

gem 'rails', '~> 5.2.3'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'redis', '~> 4.0'

gem 'bootsnap', '>= 1.1.0', require: false

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'unicorn'
gem 'unicorn-worker-killer'

gem 'factory_bot_rails'
gem 'faker'

gem 'activerecord-session_store'

gem 'devise', '~> 4.6.2'
gem 'pundit', '~> 2.0.1'

gem 'carrierwave'
gem 'mini_magick', '~> 4.8'
gem 'fog-aws', require: 'fog/aws'
gem 'unf'

gem 'resque', '~> 2.0.0'
gem 'resque-scheduler', '~> 4.4.0'
gem 'resque_mailer', '~> 2.4.3'

gem 'seed-fu', '~> 2.3'
gem 'draper'
gem 'kaminari'
gem 'config'
gem 'turnout'
gem 'enumerize', '~> 2.3.1'
gem 'ancestry'
gem 'acts_as_list'
gem 'mail-iso-2022-jp'
gem 'ransack', '~> 2.1.1'
gem 'rugged', '~> 0.28.2'
gem 'popen4'
gem 'paranoia', '~> 2.2'
gem 'virtus'
gem 'sanitize'
gem 'faraday'
gem 'faraday_middleware'
gem 'hashie'
gem 'aws-ses', require: 'aws/ses'
gem 'yajl-ruby'
gem 'rack-dev-mark'
gem 'whenever', require: false # Cron
gem 'rubyzip', require: 'zip'
gem 'rubyXL'

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring-commands-rspec'

  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails-flog', require: 'flog'
  gem 'bullet' # N+1問題の警告
  gem 'meta_request'

  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano3-unicorn'
  gem 'slackistrano'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'awesome_print'
  gem 'tapp-awesome_print'

  gem 'annotate'
  gem 'timecop'
  gem 'colorize_unpermitted_parameters'

  gem 'guard-rspec', require: false
  gem 'rspec-rails'

  gem 'letter_opener_web'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'capybara-email'
  gem 'selenium-webdriver'
  gem 'webdrivers'

  gem 'rails-controller-testing'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-collection_matchers'
  gem 'database_rewinder'
  gem 'simplecov', require: false
  gem 'shoulda-matchers'
  gem 'rspec-parameterized'
  gem 'rspec-virtus'
  gem 'rspec-retry'
  gem 'puma'
end
